version: '3.8'

services:
  client:
    build:
      context: .
      dockerfile: client/Dockerfile
      target: builder
    # Launch from root using workspace
    command: npm run start -w client -- --host 0.0.0.0 --poll 5000 --disable-host-check
    volumes:
      - .:/app
    ports:
      - "4200:4200"

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
      target: builder
    # Launch from root using workspace
    command: npm run start:dev -w server
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    env_file:
      - server/.env
